---
- hosts: "{{target}}"
  remote_user: ubuntu
  gather_facts: False
  tasks:
  - name: install python 2
    raw: test -e /usr/bin/python || (apt install -y python-minimal)
    become: true
  - name: Install apt-https, AWS cli
    apt:
      name: "{{item}}"
      state: present
    with_items:
      - apt-transport-https
      - ca-certificates
      - awscli
    become: true
  - name: Add Docker's GPG key
    shell: curl -fsSL https://yum.dockerproject.org/gpg | apt-key add -
    become: true
  - name: Add Docker repository
    shell: > 
          add-apt-repository
          "deb https://apt.dockerproject.org/repo/
          ubuntu-$(lsb_release -cs)
          main"
    become: true
  - name: Update apt
    apt:
      update_cache: yes
    become: true
  - name: Install docker-engine
    apt:
      name: docker-engine
      state: present
    become: true
  - name: Add ubuntu user to docker group
    user:
      name: ubuntu
      group: docker
    become: true
  - name: AWS Configure
    shell: printf "{{ lookup('env', 'AWS_ACCESS_KEY') }}\n{{ lookup('env', 'AWS_SECRET_KEY') }}\nus-east-1\n\n" | aws configure --profile ubuntu
